#! /bin/sh
timedatectl set-timezone America/Bogota
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap es
bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
#bspc config border_width 0.7

vmname LG3D &
vmware-user-suid-wrapper &
xsetroot -cursor_name left_ptr &
picom &
/home/blyaat/.config/polybar/launch.sh --blocks &
feh --bg-fill /home/blyaat/Descargas/4.png
